#ifndef MAP_TILE_ATTRIBUTES_H
#define MAP_TILE_ATTRIBUTES_H

enum {
    ATTRIBUTE_WALKABLE,
    ATTRIBUTE_ANIMATED,
    ATTRIBUTE_FLYABLE,
    ATTRIBUTE_WILL_BE_DRAWN,
    ATTRIBUTE_SWIMMABLE,
    ATTRIBUTE_NEED_SHIP,
    ATTRIBUTE_NEED_SUBMARINE,
    ATTRIBUTE_AIR_POISONOUS,
    ATTRIBUTE_AIR_NONE,
    ATTRIBUTE_DOOR_LOCKED
};

#endif //MAP_TILE_ATTRIBUTES_H
